Zadanie/Models/Customer.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Models.RefModels;

namespace Models
{
    [Table("tblCustomer")]
    public class Customer
    {
        [DisplayName("Dane klienta"), Column(Order = 0)]
        public int ID { get; set; }

        [DisplayName("Imię"), Column(Order = 1), Required(ErrorMessage = "To pole nie może być puste")]
        public string FirstName { get; set; }

        [DisplayName("Nazwisko"), Column(Order = 2), Required(ErrorMessage = "To pole nie może być puste")]
        public string LastName { get; set; }

        [DisplayName("Adres"), Column(Order = 3), Required(ErrorMessage = "To pole nie może być puste")]
        public string Address { get; set; }


        [DisplayName("Status klienta"), Column(Order = 4), ForeignKey("CustomerStatus")]
        public int StatusID { get; set; }
        [DisplayName("Status klienta")]
        public virtual CustomerStatus CustomerStatus { get; set; }

        [DisplayName("Emaile")]
        public virtual ICollection<Email> Emails { get; set; }
        [DisplayName("Numery")]
        public virtual ICollection<Phone> Phones { get; set; }
    }
}

Zadanie/Controllers/CustomerController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Models;
using Models.ApiModels;

namespace Controllers
{
    public class CustomerController : Controller
    {
        DBContext db = new DBContext();

        public async Task<ActionResult> Index(string searchBy, string search)
        {
            var customers = db.Customers.Include(c => c.CustomerStatus);

            switch (searchBy)
            {
                case "FirstName":
                    customers = customers.Where(c => c.FirstName.Contains(search));
                    break;
                case "LastName":
                    customers = customers.Where(c => c.LastName.Contains(search));
                    break;
                case "Address":
                    customers = customers.Where(c => c.Address.Contains(search));
                    break;

                case "Status1":
                    customers = customers.Where(c => c.CustomerStatus.Status == "Potencjalny");
                    break;
                case "Status2":
                    customers = customers.Where(c => c.CustomerStatus.Status == "Obecny");
                    break;

                case "Opcja1":
                    customers = customers.Where(c => c.Emails.Count() == 0 && c.Phones.Count() == 0);
                    break;
                case "Opcja2":
                    customers = customers.Where(c => c.Emails.Count() > 1);
                    break;

                default:
                    break;
            }

            return View(await customers.ToListAsync());
        }

        [HttpGet, ActionName("Create")]
        public ActionResult CreateOnGet()
        {
            ViewBag.StatusID = new SelectList(db.CustomerStatus, "ID", "Status");

            return View();
        }

        [HttpPost, ActionName("Create"), ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateOnPost(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Customer", null);
            }

            ViewBag.StatusID = new SelectList(db.CustomerStatus, "ID", "Status", customer.StatusID);
            return View(customer);
        }

        [HttpGet, ActionName("Details")]
        public ActionResult DetailsOnGet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var customer = db.Customers.Find(id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

        [HttpGet, ActionName("Edit")]
        public ActionResult EditOnGet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var customer = db.Customers.Find(id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            ViewBag.StatusID = new SelectList(db.CustomerStatus, "ID", "Status", customer.StatusID);
            return View(customer);
        }

        [HttpPost, ActionName("Edit"), ValidateAntiForgeryToken]
        public async Task<ActionResult> EditOnPost(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", "Customer", null);
            }

            ViewBag.StatusID = new SelectList(db.CustomerStatus, "ID", "Status", customer.StatusID);
            return View(customer);
        }

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteOnGet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var customer = db.Customers.Find(id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteOnPost(int id)
        {
            var customer = await db.Customers.FindAsync(id);
            var emails = db.Emails.Include(e => e.Customer);
            var phones = db.Phones.Include(e => e.Customer);

            {
                foreach (var e in emails)
                {
                    if (e.Customer.ID == id)
                        db.Emails.Remove(e);
                }

                foreach (var p in phones)
                {
                    if (p.Customer.ID == id)
                        db.Phones.Remove(p);
                }

                await db .SaveChangesAsync();
            }

            db.Customers.Remove(customer);
            await db .SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("SendingEmail")]
        public ActionResult SendingEmailOnGet(string mailTo, int customerID)
        {
            ViewBag.MailTo = mailTo;

            EmailToSend ets = new EmailToSend();
            ets.EmailReceiver = mailTo;

            ViewBag.CustomerID = customerID;

            return View(ets);
        }

        [HttpPost, ActionName("SendingEmail")]
        public ActionResult SendingEmailOnPost(EmailToSend ets)
        {
            using (HttpClient hc = new HttpClient())
            {
                hc.BaseAddress = new Uri("https://localhost:44389/api/EmailApi");

                var consumewebapi = hc.PostAsJsonAsync("EmailAPI", ets);

                consumewebapi.Wait();

                var sendEmail = consumewebapi.Result;
                if (sendEmail.IsSuccessStatusCode)
                    ViewBag.message = "Email został wysłany";
                else
                    ViewBag.message = sendEmail.ReasonPhrase;
            }

            return View();
        }
    }
}

Zadanie/Controllers/PhoneController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Models;
using Models.RefModels;

namespace Controllers
{
    public class PhoneController : Controller
    {
        DBContext db = new DBContext();

        [HttpGet, ActionName("Create")]
        public ActionResult CreateOnGet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var customer = db.Customers.Single(c => c.ID == id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            ViewBag.CustomerData = customer.FirstName + " " + customer.LastName + ", " + customer.Address;
            ViewBag.id = customer.ID;

            return View();
        }

        [HttpPost, ActionName("Create"), ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateOnPost([Bind(Include = "ID,PhoneContent,CustomerID")] Phone phone, int id)
        {
            var customer = await db .Customers.SingleAsync(c => c.ID == id);
            ViewBag.id = customer.ID;
            ViewBag.CustomerData = customer.FirstName + " " + customer.LastName + ", " + customer.Address;

            Phone newPhone = phone;
            newPhone.Customer = customer;

            if (ModelState.IsValid)
            {
                db.Phones.Add(phone);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Customer", new { id = id });
            }

            return View(phone);
        }

        [HttpGet, ActionName("Edit")]
        public ActionResult EditOnGet(int? id)
        {
            Phone phone = db.Phones.Find(id);
            Customer customer = db.Customers.Single(c => c.ID == phone.Customer.ID);

            ViewBag.CustomerData = customer.FirstName + " " + customer.LastName + ", " + customer.Address;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (phone == null)
            {
                return HttpNotFound();
            }

            ViewBag.CustomerID = customer.ID;

            return View(phone);
        }

        [HttpPost, ActionName("Edit"), ValidateAntiForgeryToken]
        public async Task<ActionResult> EditOnPost([Bind(Include = "ID,PhoneContent,CustomerID")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phone).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Customer", new { id = Request.Form["CustomerID"] });
            }

            return View(phone);
        }

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteOnGet(int? id)
        {
            Phone phone = db.Phones.Find(id);
            Customer customer = db.Customers.Single(c => c.ID == phone.Customer.ID);

            ViewBag.CustomerData = customer.FirstName + " " + customer.LastName + ", " + customer.Address;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (phone == null)
            {
                return HttpNotFound();
            }

            return View(phone);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteOnPost(int id)
        {
            Phone phone = await db.Phones.FindAsync(id);
            var customer = await db.Customers.SingleAsync(c => c.ID == phone.Customer.ID);
            db.Phones.Remove(phone);
            await db.SaveChangesAsync();

            return RedirectToAction("Details", "Customer", new { id = customer.ID });
        }
    }
}

Zadanie/Views/Customer/Create.cshtml
@model Models.Customer

@{
    ViewBag.Title = "Tworzenie";
}

<div style="font-family:Arial">
    <h2>Tworzenie klienta</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StatusID, null, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Stwórz" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Wróć", "Index")
    </div>

</div>

Zadanie/Views/Customer/Delete.cshtml
@model Models.Customer

@{
    ViewBag.Title = "Usuwanie";
}

<div style="font-family:Arial">
    <h2>Usuwanie klienta</h2>

    <h3>Czy na pewno chcesz usunąć klienta?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CustomerStatus.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerStatus.Status)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions">
                <input type="submit" name="Delete" value="Usuń" class="btn btn-danger" /> |
                @Html.ActionLink("Wróć do listy", "Index")
            </div>
        }
    </div>
</div>

Zadanie/Views/Customer/Details.cshtml
@model Models.Customer

@{
    ViewBag.Title = "Szczegóły";
}

<div style="font-family:Arial">
    <h2>Szczegóły klienta</h2>

    <div style="font-size:16px;">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CustomerStatus.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerStatus.Status)
            </dd>
            @Html.ActionLink("Edytuj klienta", "Edit", new { id = Model.ID })
        </dl>

        <br /><br />

        @if (Model.Emails.Count > 0)
        {
            <div>


                <table class="table" style="width:65%">
                    <tr>
                        <th width="70%">
                            Lista adresów email
                        </th>
                        <th style="text-align:center">
                            Dostępne funkcje
                        </th>
                    </tr>

                    @foreach (var item in Model.Emails)
                    {
                        <tr>
                            <td>
                                @item.EmailContent
                            </td>
                            <td style="text-align:center">
                                @Html.ActionLink("Edytuj email", "Edit", "Email", new { id = item.ID }, null) |
                                @Html.ActionLink("Usuń email", "Delete", "Email", new { id = item.ID }, null) |
                                @Html.ActionLink("Wyślij email", "SendingEmail", "Customer", new { mailTo = item.EmailContent, customerID = item.Customer.ID }, null)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        }

        @if (Model.Phones.Count > 0)
        {
            <div>
                <table class="table" style="width:65%">
                    <tr>
                        <th width="70%">
                            Lista numerów telefonu
                        </th>
                        <th style="text-align:center">
                            Dostępne funkcje
                        </th>
                    </tr>

                    @foreach (var item in Model.Phones)
                    {
                        <tr>
                            <td>
                                +48 @item.PhoneContent.Substring(0, 3) @item.PhoneContent.Substring(3, 3) @item.PhoneContent.Substring(6, 3)
                            </td>
                            <td style="text-align:center">
                                @Html.ActionLink("Edytuj numer", "Edit", "Phone", new { id = item.ID }, null) |
                                @Html.ActionLink("Usuń numer", "Delete", "Phone", new { id = item.ID }, null)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        }
        <hr />

        @Html.ActionLink("Dodaj adres email", "Create", "Email", new { id = Model.ID }, null)
        <br />
        @Html.ActionLink("Dodaj numer telefonu", "Create", "Phone", new { id = Model.ID }, null)
        <br /><br />

        <p>
            @Html.ActionLink("Wróć do listy", "Index")
        </p>

    </div>
</div>

Zadanie/Views/Customer/Edit.cshtml
@model Models.Customer

@{
    ViewBag.Title = "Edytowanie";
}

<div style="font-family:Arial">
    <h2>Edytowanie klienta</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StatusID, null, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Zapisz" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Wróć do listy", "Index") |
        @Html.ActionLink("Wróć do klienta", "Details", "Customer", new { id = Model.ID }, null)
    </div>
</div>

Zadanie/Views/Customer/Index.cshtml
@model IEnumerable<Models.Customer>

@{
    ViewBag.Title = "Strona główna";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    .textboxclass {
        height: 25px;
        width: 500px;
    }
</style>

<div style="font-family:Arial">
    <h2>
        @Html.ActionLink("Dodaj klienta", "Create")
    </h2>

    <p>
        @using (Html.BeginForm("Index", "Customer", FormMethod.Get))
        {
            <b>Szukaj po:</b>
            @Html.RadioButton("searchBy", "FirstName") <text>Imię</text>
            @Html.RadioButton("searchBy", "LastName") <text>Nazwisko</text>
            @Html.RadioButton("searchBy", "Address") <text>Adres zamieszkania</text>
            @Html.TextBox("search", null, new { @class = "textboxclass", placeholder = "Szukaj..." }) <button class="btn" type="submit" style="background-color: #b3b3b3;"><i class="fa fa-search"></i> Szukaj</button>
            <br />

            <b>Lista klientów ze statusem:</b>
            <a class="btn btn-primary" style="font-size: 12px; padding: 5px;" href="@Url.Action("Index","Customer", new { searchBy = "Status1", search = "" }, null)">Potencjalny</a>
            <a class="btn btn-primary" style="font-size: 12px; padding: 5px;" href="@Url.Action("Index","Customer", new { searchBy = "Status2", search = "" }, null)">Obecny</a>

            <br />
            <hr />
            @Html.ActionLink("Klienci nie posiadający żadnego adresu email oraz numeru telefonu", "Index", "Customer", new { searchBy = "Opcja1" }, null) <br />
            @Html.ActionLink("Klienci posiadający więcej niż jeden adres email", "Index", "Customer", new { searchBy = "Opcja2" }, null)
            <hr />
        }
    </p>
    <table class="table" border="2">
        <tr>
            <th style="text-align:center; width:13%">
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th style="text-align:center; width:13%">
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th style="text-align:center; width:13%">
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th style="text-align:center; width:6%">
                @Html.DisplayNameFor(model => model.Emails)
            </th>
            <th style="text-align:center; width:6%">
                @Html.DisplayNameFor(model => model.Phones)
            </th>
            <th style="text-align:center; width:10%">
                @Html.DisplayNameFor(model => model.CustomerStatus.Status)
            </th>
            <th style="text-align:center; width:19%">
                Dostępne funkcje
            </th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="7">Nie ma klienta z pasującym kryterium</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Emails.Count)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.Phones.Count)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.CustomerStatus.Status)
                    </td>
                    <td style="text-align:center">
                        @Html.ActionLink("Edytuj klienta", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Szczegóły", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Usuń klienta", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }
        }
    </table>
</div>

Zadanie/Views/Customer/SendingEmail.cshtml
@model Models.ApiModels.EmailToSend

<style>
    /* Style inputs, select elements and textareas */
    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        resize: vertical;
    }

    /* Style the label to display next to the inputs */
    label {
        padding: 12px 12px 12px 0;
        display: inline-block;
    }

    /* Style the submit button */
    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        float: left;
    }

    /* Style the container */
    .container2 {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }

    /* Floating column for labels: 25% width */
    .col-25 {
        float: left;
        width: 25%;
        margin-top: 6px;
    }

    /* Floating column for inputs: 75% width */
    .col-75 {
        float: left;
        width: 75%;
        margin-top: 6px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>

@using (Html.BeginForm("SendingEmail", "Customer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container2" style="width: 50%;">
        <form action="action_page.php">
            <div class="row">
                <div class="col-25">
                    <label>Odbiorca</label>
                </div>
                <div class="col-75">
                    @Html.TextBoxFor(model => model.EmailReceiver, new { @readonly = "readonly" })
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Temat</label>
                </div>
                <div class="col-75">
                    @Html.TextBoxFor(model => model.EmailSubject, new { required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Wiadomość</label>
                </div>
                <div class="col-75">
                    @Html.TextAreaFor(model => model.EmailMessage, new { rows = "13", cols = "25", @placeholder = "Twoja wiadomość..." })
                </div>
            </div>
            <div class="row" style="padding: 0px 0px 0px 15px ">
                <input type="submit" value="Wyślij">
            </div>
        </form>
    </div>

    <div>
        <br />
        @Html.ActionLink("Wróć do listy", "Index") |
        @Html.ActionLink("Wróć do klienta", "Details", "Customer", new { id = ViewBag.CustomerID }, null)
    </div>

    <h2>@ViewBag.message</h2>
}